### PR TITLE
Support for creating tar archives.

### PR DESCRIPTION
**Pull request by lehins**
This PR implements ability to create and restore tar files using a higher level abstraction that deals with file like data type `FileInfo` instead of Tar headers.

Other improvements are:
* Ability to work with files directly on the file system.
* Support for `ustar` format (file names up to 255 chars, etc.).
* Ability to create and restore files with long file names (up to 4096) by using GNU tar `L` block type
* Discard GNU tar format sparse files, same functionality as in #9 
* Fix compatibility with 32 bit OSes and 2Gb file size limit by using proper types 
* Added lts-10 to Travis
* Improved speed of stack builds on Travis by adding `.stack-work` to cache

### CODE REVIEW

**Comment by chrisdone** [comment]
How come AppVeyor was removed? There's still Windows-specific support in the project, it seems prudent to continue testing it.

**Comment by lehins** [comment]
@chrisdone There was a quick attempt to configure AppVeyor at the beginning of the PR, i.e. it was never properly setup or even close to working condition. I just didn't have time to finish it as I was setting up 5 different CI environments at the same time and it was a bit too much. I do agree thought it be good to have it setup.

**Comment by chrisdone** [comment]
No problem, then, I can contribute an AppVeyor file myself to this repo. I'm reviewing this PR presently, as I have a bunch of time opened up.

**Comment by snoyberg** [comment]
OS X builds haven't even started yet, but everything else is green. I'm going to merge and release. Thank you!

**Pull request merged**
